[theme]
base = "light"  # Options: "light" or "dark"
primaryColor = "#FFD700"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F0F0"
textColor = "#000000"
font = "sans serif"  # Options: "sans serif", "serif", or "monospace"
